#!/usr/bin/env python3
"""Probe exported A3 SONIC ONNX files.

Prints each input/output's name + shape + dtype for the 3 ONNX files
we may use for inference in PR 9. Output is saved to
  notes/a3_onnx_io_spec.md

Usage:
  cd gear_sonic_deploy
  python3 scripts/probe_a3_onnx_io.py --onnx assets/a3_runtime/models/035_step200000/model_step_200000_g1.onnx
"""
import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_EXPORT_DIR = (
    REPO_ROOT
    / "gear_sonic_deploy/assets/a3_runtime/models/035_step200000"
)

DEFAULT_CANDIDATES = ["model_step_200000_g1.onnx", "model_step_200000_a3_fast.onnx"]


def _fmt_shape(shape):
    """Format TensorShapeProto-ish into human string."""
    parts = []
    for d in shape:
        if d is None or d == 0:
            parts.append("?")
        elif isinstance(d, str):
            parts.append(d)
        else:
            parts.append(str(d))
    return "[" + ", ".join(parts) + "]"


def _probe_with_onnxruntime(path: Path):
    import onnxruntime as ort
    sess = ort.InferenceSession(str(path), providers=["CPUExecutionProvider"])
    info = {
        "path": str(path),
        "inputs": [],
        "outputs": [],
    }
    for inp in sess.get_inputs():
        info["inputs"].append({
            "name": inp.name,
            "shape": _fmt_shape(inp.shape),
            "dtype": inp.type,
        })
    for out in sess.get_outputs():
        info["outputs"].append({
            "name": out.name,
            "shape": _fmt_shape(out.shape),
            "dtype": out.type,
        })
    return info


def _probe_with_raw_onnx(path: Path):
    """Fallback: use `onnx` python package directly (no runtime)."""
    import onnx
    m = onnx.load(str(path))

    def _shape_from_ti(ti):
        if not ti.type.tensor_type.HasField("shape"):
            return ["?"]
        dims = []
        for d in ti.type.tensor_type.shape.dim:
            if d.HasField("dim_value") and d.dim_value > 0:
                dims.append(d.dim_value)
            elif d.HasField("dim_param") and d.dim_param:
                dims.append(d.dim_param)
            else:
                dims.append("?")
        return dims

    def _dtype_name(ti):
        elem_type = ti.type.tensor_type.elem_type
        # Pull from onnx TensorProto DataType
        return onnx.TensorProto.DataType.Name(elem_type) if elem_type else "?"

    info = {"path": str(path), "inputs": [], "outputs": []}
    for inp in m.graph.input:
        info["inputs"].append({
            "name": inp.name,
            "shape": _fmt_shape(_shape_from_ti(inp)),
            "dtype": _dtype_name(inp),
        })
    for out in m.graph.output:
        info["outputs"].append({
            "name": out.name,
            "shape": _fmt_shape(_shape_from_ti(out)),
            "dtype": _dtype_name(out),
        })
    # Also report IR / opset for completeness
    info["_opset"] = [f"{o.domain or 'ai.onnx'}:{o.version}" for o in m.opset_import]
    info["_ir_version"] = m.ir_version
    return info


def probe(path: Path):
    try:
        return _probe_with_onnxruntime(path)
    except ImportError:
        pass
    try:
        return _probe_with_raw_onnx(path)
    except ImportError:
        sys.exit("Neither onnxruntime nor onnx is importable. "
                 "pip install onnxruntime  (or)  pip install onnx")


def render_markdown(results, source_label):
    lines = [
        "# A3 SONIC ONNX I/O Spec",
        "",
        f"> Source: `{source_label}`",
        "",
        "Generated by `scripts/probe_a3_onnx_io.py`. This file pins the "
        "ONNX tensor schema the C++ inference pipeline (PR 9.1–9.3) must "
        "match.",
        "",
    ]
    for r in results:
        if r is None:
            continue
        lines.append(f"## `{Path(r['path']).name}`")
        lines.append("")
        if r.get("_ir_version"):
            lines.append(f"- IR version: {r['_ir_version']}")
        if r.get("_opset"):
            lines.append(f"- Opset: {', '.join(r['_opset'])}")
        lines.append("")
        lines.append("### Inputs")
        lines.append("")
        lines.append("| name | shape | dtype |")
        lines.append("|------|-------|-------|")
        for i in r["inputs"]:
            lines.append(f"| `{i['name']}` | `{i['shape']}` | `{i['dtype']}` |")
        lines.append("")
        lines.append("### Outputs")
        lines.append("")
        lines.append("| name | shape | dtype |")
        lines.append("|------|-------|-------|")
        for o in r["outputs"]:
            lines.append(f"| `{o['name']}` | `{o['shape']}` | `{o['dtype']}` |")
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--export-dir",
        type=Path,
        default=DEFAULT_EXPORT_DIR,
        help="Directory to scan when --onnx is not supplied.",
    )
    parser.add_argument(
        "--onnx",
        type=Path,
        action="append",
        default=[],
        help="Specific ONNX path to probe. Can be repeated.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("/tmp/a3_onnx_io_spec.md"),
    )
    args = parser.parse_args()

    candidates = args.onnx or [args.export_dir / name for name in DEFAULT_CANDIDATES]
    results = []
    for p in candidates:
        if not p.exists():
            print(f"[skip] {p} not found")
            results.append(None)
            continue
        print(f"[probe] {p}", flush=True)
        try:
            info = probe(p)
        except Exception as e:
            print(f"[error] {p}: {e}", file=sys.stderr)
            continue
        print(json.dumps(info, indent=2))
        print()
        results.append(info)

    source_label = ", ".join(str(p) for p in candidates)
    md = render_markdown(results, source_label)
    out_path = args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md)
    print(f"[write] {out_path}")


if __name__ == "__main__":
    main()
